### ISSUE TITLE
First steps into R

### ISSUE THREAD

**Issue by katrinleinweber** [TIBHannover/FAIR-studyGroup#10]
#### What should/will the [learning objective(s)](http://teachtogether.tech/en/process/#s:process-objectives) be?

- basic intro to RStudio
- how read your data into the very common "data frame" structure
- how to access subsets of that data, calculate statistics and draw plots

See [SwCarpentry.GitHub.io/r-novice-inflammation/01-starting-with-data](https://swcarpentry.github.io/r-novice-inflammation/01-starting-with-data/index.html). We're going to teach that 1st episode from that lesson.

#### What do participants need to know / install / bring?

Only their own computer with [RStudio already installed](https://www.rstudio.com/products/rstudio/download/#download). No prior R knowledge is needed.

---

- Oct. 10.: 8 attendees

**Comment by ChriAtive** [comment]
Hallo,
I would like to participate in the meeting tomorrow. 

Looking forward to see U,

Christine

**Comment by katrinleinweber** [comment]
Same :-) Just stop by, see "Time and location" on https://tibhannover.github.io/FAIR-studyGroup/. There is no registration or anything.

**Comment by katrinleinweber** [comment]
One other person emailed me and one called :-) We should roughly keep count, also of attendees so that we are forewarned when a bigger room becomes necessary.

**Comment by jkreklow** [comment]
I'll most likely bring one or two colleagues today

**Comment by katrinleinweber** [comment]
Closing this for now. Until a repetition is requested.

@KBurkhard & @rbirkelbach: If you are in favor of that, please leave your votes. Otherwise, please remove by clicking on them. A new event with this topic should have the same baseline votes as newly suggested topics ;-)
