### ISSUE TITLE
two ,, in session description

### ISSUE THREAD

**Issue by rbirkelbach** [TIBHannover/FAIR-studyGroup#19]
Hi,

after the title of the event, there are two `,` followed by the date. I think this should only be one `,`. It's probably because something in the session file was left out, e.g. the location and the template does not know how to deal with this.

**Comment by katrinleinweber** [comment]
Yeah, but I thought https://github.com/TIBHannover/FAIR-studyGroup/commit/d267809807af93ba39e31f8b2e73e24e6a7655c1 fixed it.

**Comment by rbirkelbach** [comment]
It's still present for me if I browse https://tibhannover.github.io/FAIR-studyGroup/

**Comment by katrinleinweber** [comment]
Fixed in 255c2a6 m-)
