### ISSUE TITLE
Announce more coworking sessions, or make this the default if no other topic is set?

### ISSUE THREAD

**Issue by katrinleinweber** [TIBHannover/FAIR-studyGroup#38]
Related to #31. We [have announced](https://tibhannover.github.io/FAIR-studyGroup/#portfolio) a few coworking sessions, but it seems tedious to make a new post for each one.

We could also add some default text like `every Wednesday, 16-18:00: coworking at Grunwald-Haus, unless other topic and location are listed`.

What do you think?

**Comment by KBurkhard** [comment]
I think your suggestion makes sense, but might not be the best strategy. Then we rely that the people read the text and not only the events....And if they only check the events, might look like there is no event in the weeks without topic. I would suggest to keep on posting the coworking session.

**Comment by katrinleinweber** [comment]
OK, will do.
